
export const Players = [
  {
    name: 'Player 1',
    amount: 5000,
    isOnline: false,
    isActive: true,
    action: '',
    actionAmount: 0,
  },
  {
    name: 'Player 2',
    amount: 5000,
    isOnline: false,
    isActive: true,
    action: '',
    actionAmount: 0,
  },
  {
    name: 'Player 3',
    amount: 5000,
    isOnline: false,
    isActive: true,
    action: '',
    actionAmount: 0,
  },
  {
    name: 'Player 4',
    amount: 5000,
    isOnline: false,
    isActive: true,
    action: '',
    actionAmount: 0,
  },
  {
    name: 'Player 5',
    amount: 5000,
    isOnline: true,
    isActive: true,
    action: '',
    actionAmount: 0,
  },
  {
    name: 'Player 6',
    amount: 5000,
    isOnline: false,
    isActive: true,
    action: '',
    actionAmount: 0,
  },
  {
    name: 'Player 7',
    amount: 5000,
    isOnline: false,
    isActive: true,
    action: '',
    actionAmount: 0,
  },
  {
    name: 'Player 8',
    amount: 5000,
    isOnline: false,
    isActive: true,
    action: '',
    actionAmount: 0,
  },
  {
    name: 'Player 9',
    amount: 5000,
    isOnline: false,
    isActive: true,
    action: '',
    actionAmount: 0,
  }
];
